import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { StrictMode } from "react";
import { App } from "@/App.tsx";
import { AppProvider } from "@/shared/store.tsx";

export function renderApp({ strictMode = false }: { strictMode?: boolean } = {}) {
  const app = (
    <AppProvider>
      <App />
    </AppProvider>
  );
  return render(
    strictMode ? <StrictMode>{app}</StrictMode> : app,
  );
}

/** Replace a field value without paying for unrelated per-character rerenders. */
export async function fillText(
  user: ReturnType<typeof userEvent.setup>,
  field: Element,
  value: string,
) {
  await user.clear(field);
  await user.click(field);
  await user.paste(value);
}

/** Append setup text while preserving a workflow prompt already generated by the UI. */
export async function appendText(
  user: ReturnType<typeof userEvent.setup>,
  field: Element,
  value: string,
) {
  await user.click(field);
  await user.keyboard("{End}");
  await user.paste(value);
}

export async function openBundle(user: ReturnType<typeof userEvent.setup>) {
  await user.click(screen.getAllByRole("button", { name: /open folder/i })[0]);
  await screen.findByRole("button", { name: /switch bundle/i });
}

export const openFolder = openBundle;

export async function openBundleAtOverview(user: ReturnType<typeof userEvent.setup>) {
  await openBundle(user);
  await user.click(screen.getByRole("treeitem", { name: /Overview/i }));
  await screen.findByRole("heading", { name: "Overview", level: 1 });
}
